// Bundled .gitignore templates, modeled after GitHub's template picker
// (github/gitignore). Content is condensed but faithful to the official
// templates for the most common ecosystems. Kept in this module so the
// backend is the single source of truth for both the template list and the
// template contents shown in the UI.

use serde::Serialize;

#[derive(Debug, Serialize, Clone)]
pub struct GitignoreTemplate {
    pub name: String,
    pub content: String,
}

const TEMPLATES: &[(&str, &str)] = &[
    (
        "Node",
        r#"# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# Build output
dist/
build/
coverage/
*.tsbuildinfo

# Environment
.env
.env.*
!.env.example

# Logs
logs/
*.log
npm-debug.log*

# Editor / OS
.DS_Store
.idea/
.vscode/
*.swp
"#,
    ),
    (
        "Python",
        r#"# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
build/
dist/
*.egg-info/
.eggs/
*.egg

# Virtual environments
.venv/
venv/
env/
ENV/

# Test / coverage
.pytest_cache/
.coverage
htmlcov/
.tox/
.nox/

# Type checkers / linters
.mypy_cache/
.pytype/
.ruff_cache/

# Environments
.env
.env.*

# IDE / OS
.idea/
.vscode/
.DS_Store
"#,
    ),
    (
        "Rust",
        r#"# Generated by Cargo
target/
**/*.rs.bk

# Build artifacts
Cargo.lock

# Editor
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
"#,
    ),
    (
        "Go",
        r#"# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of the go coverage tool
*.out

# Dependency directories
vendor/

# Go workspace file
go.work

# IDE / OS
.idea/
.vscode/
.DS_Store
"#,
    ),
    (
        "Java",
        r#"# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Virtual machine crash logs
hs_err_pid*

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
buildNumber.properties

# Gradle
.gradle/
build/

# IDE
.idea/
*.iml
.vscode/
.DS_Store
"#,
    ),
    (
        "C",
        r#"# Prerequisites
*.d

# Object files
*.o
*.ko
*.obj
*.elf

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo

# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex

# Debug Files
*.dSYM/

# IDE
.vscode/
.idea/

# OS
.DS_Store
"#,
    ),
    (
        "C++",
        r#"# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod
*.smod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app

# Build folders
build/
Debug/
Release/
x64/
x86/

# IDE
.vs/
.vscode/
.idea/

# OS
.DS_Store
"#,
    ),
    (
        "C#",
        r#"# Build results
[Dd]ebug/
[Rr]elease/
x64/
x86/
build/
bld/

# NuGet
*.nupkg
*.snupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
.nuget/

# Visual Studio
.vs/
.vsconfig
*.user
*.suo
*.userprefs
*.userosscache

# Rider
.idea/
*.sln.iml

# Build results of Roslyn analyzers
[Aa][Rr][Gg]/
[Bb]in/
[Oo]bj/

# Test results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# IDE / OS
.vscode/
.DS_Store
"#,
    ),
    (
        "Ruby",
        r#"# Bundler
.bundle/
vendor/bundle/

# Environment
.env

# Test
spec/examples.txt
coverage/
tmp/

# Rails
log/*.log
log/tmp/
tmp/cache/
tmp/sockets/
tmp/pids/
tmp/storage/

# Editor / OS
.idea/
.vscode/
.DS_Store
"#,
    ),
    (
        "PHP",
        r#"# Composer
vendor/
composer.phar

# Laravel
.env
.env.*
*.log
storage/*.key
storage/logs/*
public/build

# PHPUnit
.phpunit.result.cache
.phpunit.cache

# IDE / OS
.idea/
.vscode/
.DS_Store
"#,
    ),
    (
        "Swift",
        r#"# Xcode
DerivedData/
*.xcuserstate
xcuserdata/

# Swift Package Manager
.build/
.build/
.swiftpm/

# CocoaPods
Pods/

# Carthage
Carthage/Build/

# IDE
.idea/
.vscode/

# OS
.DS_Store
"#,
    ),
    (
        "Kotlin",
        r#"# Gradle
.gradle/
build/

# Kotlin
.kotlin/

# IntelliJ IDEA
.idea/
*.iml
*.ipr
*.iws

# Android
local.properties
captures/
.externalNativeBuild/
.cxx/

# OS
.DS_Store
"#,
    ),
    (
        "macOS",
        r#"# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon


# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
"#,
    ),
    (
        "Windows",
        r#"# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk
"#,
    ),
    (
        "Linux",
        r#"# Compiled source
*.com
*.class
*.dll
*.exe
*.o
*.so

# Packages
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Logs and databases
*.log
*.sql
*.sqlite

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
"#,
    ),
    (
        "VisualStudioCode",
        r#"# VS Code
.vscode/*
!.vscode/extensions.json
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# Local History for Visual Studio Code
.history/

# OS
.DS_Store
"#,
    ),
    (
        "JetBrains",
        r#"# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio, WebStorm, Rider

# User-specific
*.iml
*.ipr
*.iws
.idea/
**/out/
**/shelf/
.idea/workspace.xml
.idea/tasks.xml
.idea/httpRequests/

# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Gradle
.gradle/
build/

# OS
.DS_Store
Thumbs.db
"#,
    ),
    (
        "SublimeText",
        r#"# Cache files for Sublime Text
*.tmlanguage.cache
*.st-cache

# Workspace files are user-specific
*.sublime-workspace

# Project files should be checked out, if you want to
# keep the project settings
# *.sublime-project

# SFTP configuration file
sftp-config.json
sftp-config-alt*.json

# Package control must be ignored
Packages/User/
"#,
    ),
    (
        "Dotenv",
        r#"# Environments
.env
.env.*
!.env.example
!.env.test

# Local
*.local

# Secrets
*.pem
*.key
*.secret
*_rsa
*_dsa
"#,
    ),
    (
        "Terraform",
        r#"# Local .terraform directories
**/.terraform/*
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all .tfvars files
*.tfvars
*.tfvars.json

# Ignore override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Include tfplan files to ignore the plan output
*.tfplan

# IDE / OS
.idea/
.vscode/
.DS_Store
"#,
    ),
    (
        "Vue",
        r#"# Dependencies
node_modules/

# Build output
dist/
dist-ssr/
*.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# OS
.DS_Store
"#,
    ),
    (
        "React",
        r#"# Dependencies
node_modules/

# Testing
coverage/
.tmp/

# Production
build/
dist/

# Misc
.DS_Store
*.pem
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.idea/
.vscode/
*.swp

# Environment
.env
.env.*
"#,
    ),
    (
        "Unity",
        r#"# Unity generated
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
*.pidb.meta
*.pidb
*.pdb.meta
*.pdb
*.mdb.meta
*.mdb

# Unity3D generated meta files
*.unitymeta

# Crashlytics generated file
crashlytics-build.properties

# IDE
.vs/
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"#,
    ),
];

pub fn list() -> Vec<GitignoreTemplate> {
    TEMPLATES
        .iter()
        .map(|(name, content)| GitignoreTemplate {
            name: name.to_string(),
            content: content.to_string(),
        })
        .collect()
}
